#!/usr/bin/env python3
# -*- coding: utf-8 -*-

##########################################################################
#
# w2kplot: a thin Python wrapper around matplotlib
#
# Copyright (C) 2022 Harrison LaBollita
# Authors: H. LaBollita
#
# w2kplot is free software licensed under the terms of the MIT license.
#
##########################################################################

from w2kplot.utils import fs_gen


if __name__ == "__main__":
    raise NotImplementedError
