#!/usr/bin/env python3
# -*- coding: utf-8 -*-

##########################################################################
#
# w2kplot: a thin Python wrapper around matplotlib
#
# Copyright (C) 2022 Harrison LaBollita
# Authors: H. LaBollita
#
# w2kplot is free software licensed under the terms of the MIT license.
#
##########################################################################

from w2kplot.utils import kpath_gen


if __name__ == "__main__":

    raise NotImplementedError

    #for k in kvecs:
    #    kx, ky, kz = k
    #    print( str(kx).rjust(15), str(ky).rjust(4), str(kz).rjust(4), str(div).rjust(4), '1.0'.rjust(4))
    #print('END')
