#!/usr/bin/python3
from spaghetti.core.bands import bands
from spaghetti.core.parse import parse


def main(args):
    bands(args)

if __name__ == "__main__":
    args = parse()
    for key, value in args.__dict__.items():
        print("{}:    {}".format(key, value))
    main(args)
