#!/usr/bin/env python
#from spaghetti.core.bands import bands
#from spaghetti.core.parse import parse
import glob, sys
from spaghetti.src.struct import *


def command_line():
    import argparse
    parser=argparse.ArgumentParser()
    parser.add_argument("--init", dest="init", action="store_true", help="sets up the interactive initialization to create the plot")
    parser.add_argument("--bands", dest="bands", action="store_true", help="only plots the bands (no fatbands!)")
    parser.add_argument("--ymin", type = float, default = -1.5)
    parser.add_argument("--ymax", type = float, default = 1.5)
    parser.add_argument("--weight", type=int, default=20, help = "weights multiply character by")
    parser.add_argument("--save", default = None, help = "option to save the image")
    args = parser.parse_args()
    return args

def init():
    """interactive intialization of the input file."""
    structure=struct()
    klabels=input("Enter the klabels that you would like to use (Ex - Gamma X M Gamma): ")
    fatband=input("Do you wish to plot fatbands? (y/n) ")
    if fatband == "y":
        if len(glob.glob("*.qtl")) == 0:
            print("you will need a qtl file for this!")
            sys.exit(1)
        if len(glob.glob("*.struct")) == 0:
            print("you will need a struct file for this!")
            sys.exit(1)
        msg="""From the available struct file:  {} We found the following:.""".format(structure.filename)
        print(msg)
        for ia, a in enumerate(structure.atoms):
            print("{:^5s} {:^5s} {:^5s}".format(str(ia+1), str(structure.atoms[a][0]), str(structure.atoms[a][1])))
        atoms=list(map(int, input("Please enter a list of atoms: ").split()))
        print("""Now enter the index of the orbital that you would like to plot.""")
        orbitals=[list(map(int, input("orbital-character for atom {}: ".format(a)))) for a in atoms]


if __name__ == "__main__":
    args = command_line()
    if args.init:
        init()
